/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javatestapp;

/**
 *
 * @author Arkham
 */
public class TestJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestJFrame
     */
    public TestJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Panel = new javax.swing.JPanel();
        Calc_Input = new javax.swing.JTextField();
        AC_Button = new javax.swing.JButton();
        Divide_Button = new javax.swing.JButton();
        Brackets_Button = new javax.swing.JButton();
        Percentage_Button = new javax.swing.JButton();
        Multiply_Button = new javax.swing.JButton();
        Minus_Button = new javax.swing.JButton();
        Addition_Button = new javax.swing.JButton();
        Equal_Button = new javax.swing.JButton();
        Num7_Button = new javax.swing.JButton();
        Num8_Button = new javax.swing.JButton();
        Num9_Button = new javax.swing.JButton();
        Num6_Button = new javax.swing.JButton();
        Num3_Button = new javax.swing.JButton();
        Backspace_Button = new javax.swing.JButton();
        Num4_Button = new javax.swing.JButton();
        Num5_Button = new javax.swing.JButton();
        Num2_Button = new javax.swing.JButton();
        Period_Button = new javax.swing.JButton();
        Num1_Button = new javax.swing.JButton();
        Zero_Button = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Calc_Input.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Calc_Input.setActionCommand("<Not Set>");
        Calc_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_InputActionPerformed(evt);
            }
        });

        AC_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AC_Button.setText("AC");
        AC_Button.setAutoscrolls(true);
        AC_Button.setName(""); // NOI18N

        Divide_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Divide_Button.setText("/");
        Divide_Button.setAutoscrolls(true);
        Divide_Button.setName(""); // NOI18N
        Divide_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Divide_ButtonActionPerformed(evt);
            }
        });

        Brackets_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Brackets_Button.setText("( )");
        Brackets_Button.setAutoscrolls(true);
        Brackets_Button.setName(""); // NOI18N
        Brackets_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Brackets_ButtonActionPerformed(evt);
            }
        });

        Percentage_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Percentage_Button.setText("%");
        Percentage_Button.setAutoscrolls(true);
        Percentage_Button.setName(""); // NOI18N
        Percentage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Percentage_ButtonActionPerformed(evt);
            }
        });

        Multiply_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Multiply_Button.setText("x");
        Multiply_Button.setAutoscrolls(true);
        Multiply_Button.setName(""); // NOI18N

        Minus_Button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Minus_Button.setText("-");
        Minus_Button.setAutoscrolls(true);
        Minus_Button.setName(""); // NOI18N
        Minus_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minus_ButtonActionPerformed(evt);
            }
        });

        Addition_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Addition_Button.setText("+");
        Addition_Button.setAutoscrolls(true);
        Addition_Button.setName(""); // NOI18N

        Equal_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Equal_Button.setText("=");
        Equal_Button.setAutoscrolls(true);
        Equal_Button.setName(""); // NOI18N
        Equal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equal_ButtonActionPerformed(evt);
            }
        });

        Num7_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num7_Button.setText("7");
        Num7_Button.setAutoscrolls(true);
        Num7_Button.setName(""); // NOI18N
        Num7_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7_ButtonActionPerformed(evt);
            }
        });

        Num8_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num8_Button.setText("8");
        Num8_Button.setAutoscrolls(true);
        Num8_Button.setName(""); // NOI18N
        Num8_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8_ButtonActionPerformed(evt);
            }
        });

        Num9_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num9_Button.setText("9");
        Num9_Button.setAutoscrolls(true);
        Num9_Button.setName(""); // NOI18N
        Num9_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num9_ButtonActionPerformed(evt);
            }
        });

        Num6_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num6_Button.setText("6");
        Num6_Button.setAutoscrolls(true);
        Num6_Button.setName(""); // NOI18N

        Num3_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num3_Button.setText("3");
        Num3_Button.setAutoscrolls(true);
        Num3_Button.setName(""); // NOI18N
        Num3_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3_ButtonActionPerformed(evt);
            }
        });

        Backspace_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Backspace_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javatestapp/backspace.png"))); // NOI18N
        Backspace_Button.setAutoscrolls(true);
        Backspace_Button.setName(""); // NOI18N

        Num4_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num4_Button.setText("4");
        Num4_Button.setAutoscrolls(true);
        Num4_Button.setName(""); // NOI18N
        Num4_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4_ButtonActionPerformed(evt);
            }
        });

        Num5_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num5_Button.setText("5");
        Num5_Button.setAutoscrolls(true);
        Num5_Button.setName(""); // NOI18N
        Num5_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5_ButtonActionPerformed(evt);
            }
        });

        Num2_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num2_Button.setText("2");
        Num2_Button.setAutoscrolls(true);
        Num2_Button.setName(""); // NOI18N

        Period_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Period_Button.setText(".");
        Period_Button.setAutoscrolls(true);
        Period_Button.setName(""); // NOI18N
        Period_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Period_ButtonActionPerformed(evt);
            }
        });

        Num1_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Num1_Button.setText("1");
        Num1_Button.setAutoscrolls(true);
        Num1_Button.setName(""); // NOI18N
        Num1_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1_ButtonActionPerformed(evt);
            }
        });

        Zero_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Zero_Button.setText("0");
        Zero_Button.setAutoscrolls(true);
        Zero_Button.setName(""); // NOI18N
        Zero_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zero_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calc_Input)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(AC_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Brackets_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Percentage_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Divide_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Num7_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Num8_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num9_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(Num4_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Num5_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Num1_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Zero_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Num2_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Period_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num6_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num3_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Backspace_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Multiply_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Minus_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Addition_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Equal_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Calc_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AC_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Divide_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Brackets_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Percentage_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(Multiply_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Minus_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Addition_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Equal_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Num9_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num7_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num8_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Num6_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num3_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Backspace_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Num5_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num4_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(Num2_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Period_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(Num1_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Zero_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AC_Button.getAccessibleContext().setAccessibleName("AC_Button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Calc_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Calc_InputActionPerformed

    private void Brackets_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Brackets_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Brackets_ButtonActionPerformed

    private void Percentage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Percentage_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Percentage_ButtonActionPerformed

    private void Minus_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minus_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minus_ButtonActionPerformed

    private void Equal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equal_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Equal_ButtonActionPerformed

    private void Divide_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Divide_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Divide_ButtonActionPerformed

    private void Num7_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num7_ButtonActionPerformed

    private void Num8_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num8_ButtonActionPerformed

    private void Num9_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num9_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num9_ButtonActionPerformed

    private void Num3_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num3_ButtonActionPerformed

    private void Num4_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num4_ButtonActionPerformed

    private void Num5_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num5_ButtonActionPerformed

    private void Period_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Period_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Period_ButtonActionPerformed

    private void Zero_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zero_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Zero_ButtonActionPerformed

    private void Num1_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num1_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC_Button;
    private javax.swing.JButton Addition_Button;
    private javax.swing.JButton Backspace_Button;
    private javax.swing.JButton Brackets_Button;
    private javax.swing.JTextField Calc_Input;
    private javax.swing.JButton Divide_Button;
    private javax.swing.JButton Equal_Button;
    private javax.swing.JButton Minus_Button;
    private javax.swing.JButton Multiply_Button;
    private javax.swing.JButton Num1_Button;
    private javax.swing.JButton Num2_Button;
    private javax.swing.JButton Num3_Button;
    private javax.swing.JButton Num4_Button;
    private javax.swing.JButton Num5_Button;
    private javax.swing.JButton Num6_Button;
    private javax.swing.JButton Num7_Button;
    private javax.swing.JButton Num8_Button;
    private javax.swing.JButton Num9_Button;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton Percentage_Button;
    private javax.swing.JButton Period_Button;
    private javax.swing.JButton Zero_Button;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
